- name: install DisplayLink manager
  hosts: desktops
  tasks:
  - name: Synaptics apt key
    apt_key:
      data: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBGM76wkBEAC5dcDFny5/OAMyzs68hLNriNDIzaW7oAHJPzTEduqmNx4Tu5ZV
        efll5BtcyU4yHQmBS7v2ruqe+GaGtxBoE3SZUJDugECzaLBMLFSTcw1ACQOg15QH
        4vNVoEp6H4tz9AQuP0MMdUKKN07sxGQhUL58dJPnpZxfAiEsd5nLQfDE1wcP4Dom
        I8CCBkDEwqXmItrfOzkseXraBniBZwDOybg9vdR1SsC1lZQhtOWYB1rMCeNpE5Y/
        GTWeQFuljGokZss8JoUMgpLXhEA50v8NGOhv5sT0kbxAMWI4gu32CZv8myqAqefK
        lpYiBsEfz8Noak2tG3V4RsE9UfwbTk8MrP9JObD9kGMu3lq+mgqUFtA4cyspjY6m
        vbbLzAClAYB1quaYCwqUIC+PnYJlSNWPe117I6rDdtRZ/+KlMUJJsGTogNKFIRMW
        WMy1vdHAeefw00jnWsz7uDZ+/86JOMLG4wojaJsQy8+/0n5x/HpzvR1AVKjPDciK
        Tm0qHv4+eI5zh1QI9ctd6oMdnUQFbmKQWYqoOna8ADEXrxYqRPg9BqV1Iec/378V
        MvJL81Ur2xkRuWUcELl/K5XaobPoOLURoslpVGDqiuVUPq06nOvwn4hDvn/za4SJ
        SOUQX7dOBvoicX1nWXwH8l7Zl90Qm4K4X7FSDga7YSQ3deQP1jma9qa/xQARAQAB
        tK9TeW5hcHRpY3MgRGlzcGxheUxpbmsgRHJpdmVyIFB1YmxpYyBSZXBvc2l0b3J5
        IFNpZ25pbmcgS2V5IChTeW5hcHRpY3MgSW5jLiBTeW5hcHRpY3MgVGVjaG5pY2Fs
        IFN1cHBvcnQgPHRlY2huaWNhbC1lbnF1aXJpZXNAc3luYXB0aWNzLmNvbT4pIDx0
        ZWNobmljYWwtZW5xdWlyaWVzQHN5bmFwdGljcy5jb20+iQJUBBMBCAA+FiEEXOwO
        g+T2qLoFd5JyOs+qZaiS5aUFAmM76wkCGy8FCQlmAYAFCwkIBwIGFQoJCAsCBBYC
        AwECHgECF4AACgkQOs+qZaiS5aWtqBAAuNt6T+X0yafUvJXeM/aDPOsTja5ZPH5J
        /+5kVkxs8hH9R2pvdbK2kHIaNBMrdhxc3dyUNySBeqylnU6bwjDv4BA7hkPnMjJ4
        yU3mXmozglqH2dPEF3Hy3Nyt2y15wAEvoCJBF0wOXkD74utHYj2Au1sbcSBKzkOB
        7gS3WqcBAZ3aoO211JFpjPAHCGH+4aIlu64vzZvsXi6PFkxH1qPNc4RJ+DmeHaPQ
        qAYxvzSrm/Jb4GMIw9/0EbwGvx/4MWGt/qtDDWW54HYxiy4HHflx1znRVUqnAP5L
        w91WxnMmUTtqwO57f3hXQ/pVBD5UniNEp53ofj2KdpN+qbuWW8lUmUZS8Q2MsEuz
        CUNe+Fja8g/ZbOS868zO3PaTi2Fvqx5KOXrCcgJaYzv21UJcc9mtgfhk6Dz7u5mU
        bvDHgVapMml94fc7JlLhYsDh4iyXgYwPuwa+of6+oOhU82y3bB4DA85ryvBZ0Ran
        Dghp5T7QZT8xglveuPkII36dKmDQcZGKTqhbUysYbEF0hdNmZZUh9G1JojRWkt+z
        yj7KVrItcwY4Qs+m6FwTmJQ5MGTT9/SevKHhWBaI3/ovUy0YHd1dmtpRtdHzZfoB
        iJIDMdeejuUtgRJ2Ood+hUiUwPxK9I5Ek0ePqPDQ9SKdOMZr1OwAHLxQ9In0SZ0j
        lVsu1a+O7Oc=
        =u/Bz
        -----END PGP PUBLIC KEY BLOCK-----
      keyring: /etc/apt/trusted.gpg.d/synaptics.gpg

  - name: Synaptics main apt repository
    apt_repository:
      filename: /etc/apt/sources.list.d/synaptics
      repo: 'deb https://www.synaptics.com/sites/default/files/Ubuntu/ stable main'
      update_cache: no
    register: aptsynapticsmain

  - name: Synaptics non-free apt repository
    apt_repository:
      filename: /etc/apt/sources.list.d/synaptics
      repo: 'deb https://www.synaptics.com/sites/default/files/Ubuntu/ stable non-free'
      update_cache: no
    register: aptsynapticsnonfree

  - name: Update apt repository for Synaptics
    command: apt update
    changed_when: False
    when: aptsynapticsmain.changed or aptsynapticsnonfree.changed

  - name: Install DisplayLink driver
    apt: name=displaylink-driver
    register: driverinstalled

  - name: prompt for reboot if DisplayLink was installed
    fail: msg='Please reboot and rerun playbook'
    when: driverinstalled.changed
