---
- name: set hostname
  hosts: desktops
  tasks:
  - name: set hostname in kernel
    hostname: name='{{inventory_hostname}}'
  - name: set hostname in /etc/hosts
    replace:
      dest: /etc/hosts
      regexp: '^(\s*127\.0\.0\.1\s+(?!.*{{inventory_hostname}}))'
      replace: '\1{{inventory_hostname}} '
