- import_playbook: etherwake.yml

- hosts: desktops
  vars:
    dir: /home/jik/src/family-orchestration
    real: "{{dir}}/secrets.yml"
    tmp: "{{real}}.tmp"
  tasks:
  - name: Copy temporary secrets to remote
    copy:
      src: "{{real}}"
      dest: "{{tmp}}"
    changed_when: false

  - name: Compare local and remote secrets
    script: compare_yaml.py {{real}} {{tmp}}
    args:
      chdir: "{{dir}}"
      executable: python3
    changed_when: false
    failed_when: false
    register: compare

  - name: Replace secrets on remote
    copy:
      remote_src: true
      src: "{{tmp}}"
      dest: "{{real}}"
    when: compare.rc == 2

  - fail: msg="Remote host has new secrets"
    when: compare.rc == 1

  - fail: msg="Local and remote have conflicting secrets"
    when: compare.rc not in [0, 1, 2]

  - name: Delete temporary secrets from remote
    file:
      path: "{{tmp}}"
      state: absent
    changed_when: false

  - name: fix permissions on secrets.yml
    file:
      path: "{{real}}"
      mode: 0600
