- hosts: desktops
  gather_facts: no
  vars:
    tburl: https://archive.mozilla.org/pub/thunderbird/releases/78.9.1/linux-x86_64/en-US/thunderbird-78.9.1.tar.bz2
    tbdir: /home/jik/bin/tb78
  tasks:
  - name: get facts
    setup:
    when: ansible_date_time is not defined

  - name: create {{tbdir}}
    file:
      path: "{{tbdir}}"
      state: directory
      owner: jik
      group: jik

  - name: download {{tburl}}
    get_url:
      dest: /tmp/{{tburl|basename}}
      url: "{{tburl}}"

  - name: untar {{tburl}}
    unarchive:
      dest: "{{tbdir}}"
      src: "/tmp/{{tburl|basename}}"
      extra_opts: ["--strip-components=1"]
      owner: jik
      group: jik
