- hosts: desktops
  gather_facts: no
  tasks:
  - name: get facts
    setup:
    when: ansible_date_time is not defined

  - name: check if Thunderbird is installed in my home directory
    stat: path=/home/jik/bin/.tb-mozilla-download-current/thunderbird
    register: tbcurrent

  - when: not tbcurrent.stat.exists
    block:
    - name: create Thunderbird directory
      file:
        path: /home/jik/bin/.tb-mozilla-download-current
        state: directory
        owner: jik
        group: jik

    - name: download Thunderbird
      get_url:
        dest: /tmp/{{tburl|basename}}
        url: "{{tburl}}"
      register: downloaded
      
    - name: untar Thunderbird
      unarchive:
        dest: /home/jik/bin/.tb-mozilla-download-current
        src: "/tmp/{{tburl|basename}}"
        extra_opts: ["--strip-components=1"]
        owner: jik
        group: jik

    - name: create Thunderbird symlink
      file:
        path: /home/jik/bin/thunderbird
        src: /home/jik/bin/.tb-mozilla-download-current/thunderbird
        state: link
        owner: jik
        group: jik

  - name: create Thunderbird desktop file
    copy:
      dest: /home/jik/.local/share/applications/jik-thunderbird.desktop
      owner: jik
      group: jik
      content: |
        [Desktop Entry]
        Name=Jik Thunderbird
        Comment=Read/Write Mail/News with Thunderbird
        GenericName=Mail Client
        Exec=/home/jik/bin/thunderbird --class jik-thunderbird %u
        Terminal=false
        X-MultipleArgs=false
        Type=Application
        Version=1.0
        Icon={{thunderbird_icon}}
        Categories=Network;Email;News;GTK;
        MimeType=message/rfc822;x-scheme-handler/mailto;text/calendar;text/x-vcard;
        StartupWMClass=jik-thunderbird
        StartupNotify=true
        Keywords=EMail;E-mail;Contact;Addressbook;News;
        Actions=Compose;Contacts

        [Desktop Action Compose]
        Name=Compose New Message
        Exec=/home/jik/bin/thunderbird -compose

        [Desktop Action Contacts]
        Name=Contacts
        Exec=/home/jik/bin/thunderbird -addressbook
    register: tbdesktop

  - name: update desktop database after creating Thunderbird desktop file
    command: update-desktop-database /home/jik/.local/share/applications
    when: tbdesktop.changed

  - name: Add message/rfc822 to mimeapps.list for Thunderbird
    ini_file:
      path: /home/jik/.config/mimeapps.list
      section: Default Applications
      option: message/rfc822
      value: jik-thunderbird.desktop
      owner: jik
      group: jik
      no_extra_spaces: true

  - name: Add mailto to mimeapps.list for Thunderbird
    ini_file:
      path: /home/jik/.config/mimeapps.list
      section: Added Associations
      option: x-scheme-handler/mailto
      value: "jik-thunderbird.desktop;"
      owner: jik
      group: jik
      no_extra_spaces: true
  
  - name: check if TB102 is installed in my home directory
    stat: path=/home/jik/bin/tb102/thunderbird
    register: tbcurrent

  - name: check if TB102 version is current
    ini_file:
      path: /home/jik/bin/tb102/application.ini
      section: App
      option: Version
      value: "{{tb102version}}"
      no_extra_spaces: true
    check_mode: True
    register: tbversion

  - when: tbversion.changed or not tbcurrent.stat.exists
    block:
    - name: create TB102 directory
      file:
        path: /home/jik/bin/tb102
        state: directory
        owner: jik
        group: jik

    - name: download Thunderbird 102
      get_url:
        dest: /tmp/{{tb102url|basename}}
        url: "{{tb102url}}"
      register: downloaded
      
    - name: untar Thunderbird 102
      unarchive:
        dest: /home/jik/bin/tb102
        src: "/tmp/{{tb102url|basename}}"
        extra_opts: ["--strip-components=1"]
        owner: jik
        group: jik

  - name: Create TB102 policy directory
    file:
      path: /home/jik/bin/tb102/distribution
      state: directory
      owner: jik
      group: jik

  - name: Deploy TB102 policy to disable updates
    copy:
      dest: /home/jik/bin/tb102/distribution/policies.json
      content: |
        {
         "policies": {
           "AppAutoUpdate": false
         }
        }      
      owner: jik
      group: jik
      
  - name: Add daily job to back up Thunderbird data
    copy:
      dest: /etc/cron.daily/jik-thunderbird-backup
      mode: 755
      content: |
        #!/bin/sh -e
        su - jik -c ~jik/src/scripts/thunderbird-data-backup.sh

