---
- hosts: blog
  tasks:

  - name: install certbot CLI
    yum:
      name:
      - certbot
      - python3-certbot-apache

  - name: install certbot cron job
    copy:
      content: |
        #!/bin/bash -e
        LOGFILE=/tmp/certbot-auto-renew-$(date +%F).log
        trap "cat $LOGFILE 1>&3" EXIT
        exec >> $LOGFILE 3>&2 2>&1
        set -x
        certbot renew \
            --standalone \
            --pre-hook "service httpd stop && sleep 5" \
            --post-hook "service httpd start"
        chgrp -R sslservers /etc/letsencrypt
        chmod -R g+rX,g-w,o-rwx /etc/letsencrypt
        find /etc/letsencrypt -type d -print0 | xargs -0 chmod g+s
        if grep -q -s '^Running post-hook command' $LOGFILE; then
            service cyrus-imapd restart
            service sendmail restart
        fi
        trap "" EXIT
      dest: /etc/cron.weekly/certbot-auto-renew
      mode: 0755
